image: andrewdagostino/cis4250-ci:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.cache/pip/

before_script:
  - python -V
  - pip install -r src/api/requirements.txt

stages:
  - test

Test:
  stage: test
  script:
    - pytest --cov=src/api/classes/ --cov=src/api/functions/ src/api/test/ --junitxml=report.xml
  variables:
    SCRAPE: "OFF"
  coverage: /^TOTAL.+?(\d+\%)$/
  artifacts:
    when: always
    reports:
      junit: report.xml
  only:
    refs:
      - branches