image: python:3.9-slim-buster

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.cache/pip/

before_script:
  - python -V
  - apt-get update
  - apt-get install -y poppler-utils
  - pip install -r backend/requirements.txt

test:
  script:
    - pytest --cov=backend/classes/ --cov=backend/functions/ backend/test/
  variables:
    SCRAPE: "OFF"
  coverage: /^TOTAL.+?(\d+\%)$/
  only:
    refs:
      - branches
